name: 'Captain CI example'
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        partition_index: [0, 1]
        partition_total: [2]
    steps:
      - uses: actions/checkout@v3
      - uses: rwx-research/setup-captain@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          config: "video=false"
          command-prefix: |
            test_files=$(
              captain partition \
              --suite-id captain-examples-cypress \
              --index ${{ matrix.partition_index }} \
              --total ${{ matrix.partition_total }} \
              --delimiter ',' \
              "cypress/**/*.cy.js"
            )
            captain run \
              --suite-id captain-examples-cypress \
              --test-results "tmp/junit/*.xml" \
              --language JavaScript \
              --framework Cypress \
              --github-job-matrix '${{ toJSON(matrix) }}' \
              --
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
